language: node_js
node_js:
- '9.7.1'
services:
- mongodb
cache:
  directories:
    - app/node_modules
    - frontend/node_modules
    - app/plugins
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: austinberke/mim
  bucket: mim-deploy
  region: us-west-2
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: mim-deploy
  key: latest.zip
  bundle_type: zip
  application: mim
  deployment_group: mim-server
  region: us-west-2
  on: *2
script:
  - zip -rq latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
