version: "2"
services:
  frontend:
    container_name: frontend
    restart: always
    build: ./frontend
    ports:
      - "1338:80"
    links:
      - app
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "1337:1337"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
